### ISSUE TITLE
Spatially non-overlapping input salience

### ISSUE THREAD

**Issue by bikeboi** [bikeboi/jra-project#1]
Spatially non-overlapping inputs may not have as much intra-class saliency due to random PN->KC connectivity. Without a topographical mapping from inputs to KCs, spatial information may be lost in transduction.

**Comment by chanokin** [comment]
> Spatially non-overlapping inputs may not have as much intra-class saliency due to random PN->KC connectivity. Without a topographical mapping from inputs to KCs, spatial information may be lost in transduction.

What do you mean by topographical mapping?

**Comment by bikeboi** [comment]
> > Spatially non-overlapping inputs may not have as much intra-class saliency due to random PN->KC connectivity. Without a topographical mapping from inputs to KCs, spatial information may be lost in transduction.
> 
> What do you mean by topographical mapping?

I had an idea to structure the PN->KC connections to have tuning structure, where PNs close together project to KCs close together (similar to retinal neurons onto V1 cortex); the tuning would be periodic, with every n KC responding similarly to the same PN, like orientation tuned neurons in V1 cortex. I thought this may help with random inputs having little salience. However, due to both the decision to use real character inputs and the absence of noticeably structured PN->KC pathways in real insects, I reckon this is over-complicating things. I'll close the issue
